BUG:canonicalize_file_name not supported on MAC OS
GobySoft/goby pull request #18
Opened 2017-03-02 18:35 UTC by tfabbri

canonicalize_file_name not supported in Mac Os systems.
Used to boost::filesystem::canonical to overcome this limitation.

This fix has to be tested on Ubuntu systems.

2017-03-02 18:46 UTC, tsaubergine commented
Thanks for suggesting contributions to Goby. Since this is your first contribution, we need to you to accept the Contributor License Agreement (see https://github.com/GobySoft/goby/blob/2.1/AUTHORS). As explained in the AUTHORS file, please add your name to the AUTHORS file and include this commit in your pull request.

2017-03-02 18:47 UTC, tsaubergine requested changes

2017-03-02 18:47 UTC, tsaubergine commented on src/common/application_base.cpp
> +namespace fs = boost::filesystem;
Please move to the required scope (such as right before line 125).

2017-03-02 18:47 UTC, tsaubergine commented on src/common/application_base.cpp
> +       //symlink(canonicalize_file_name(file_name.c_str()), file_symlink.c_str());
Please remove this commented-out line

2017-03-02 18:47 UTC, tsaubergine commented
A few minor changes and I'll merge this.

Thanks-
-Toby

2017-03-02 19:11 UTC, tfabbri commented
Done

2017-03-02 19:36 UTC, tsaubergine approved these changes

2017-03-02 19:36 UTC, merged

2017-03-03 21:49 UTC, tsaubergine commented
@tfabbri This change is broken. In the future please test any changes before putting in a pull request.